### ISSUE TITLE
no spacing between filter elements and table in projects_html

### ISSUE THREAD

**Issue by l-with** [l-with/terraform-module-gitlab-doc#6]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/53109379/191682051-798aa532-20f8-4211-b237-724c49e1c7ca.png">

There should spacing as in users_html.

**Comment by VedshreeB** [comment]
@l-with I would like to work on this issue. 
I have fixed these types of issues earlier in my own projects.
assigned it to me

**Comment by l-with** [comment]
@VedshreeB I am very happy about your suggestion. I must apologise, I am just starting with collaboration on my own GitHub-projects. I missed to assign myself. There is already a PR for this issue: https://github.com/l-with/terraform-module-gitlab-doc/pull/7

You are very welcome to help with the further development!
